# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @describeIn aggregationFunction_bootLM Run bootstrapped linear regression in Rcpp.
bootLM <- function(x, y, boot_iter = 100L) {
    .Call('_ensembleR_bootLM', PACKAGE = 'ensembleR', x, y, boot_iter)
}

