# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name BootLM
#' @export
#' @title Bootstrap LM
#' @description C++ implementation of the bootstrapping LM loop used in
#' \link[ensembleR]{fitAggregationFunction_bootLM}. This function is not
#' intended to be called directly.
#' @param x A numeric matrix of features
#' @param y A numeric vector of the response variable
#' @param boot_iter An integer specifying the number of bootstrap iterations.
bootLM <- function(x, y, boot_iter = 1000L) {
    .Call('_ensembleR_bootLM', PACKAGE = 'ensembleR', x, y, boot_iter)
}

